# Generated by Django 5.0.7 on 2024-07-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_selectedplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedplayer',
            name='position',
        ),
    ]
